### ISSUE TITLE
anchor, end-of-preview

### ISSUE THREAD

**Issue by seonae** [webkini/bxp-sublime-syntax#1]
=(anchor|anchor_id)=
=(end-of-preview)=
추가 해주세요.

예시)
=begin page
dkjlㅇㅇf =(anchor|ipad_1)= 텍스트블라브ㅏ르ㅏ브
=(end-of-preview)=
=object video: filename=ipad_1.mp4, style=video, url="ipad_2", preview="preview_ipad_2.jpg", action=link, url="anchor:ipad_2"
=end
=(anchor|ipad_2)=

**Comment by webkini** [comment]
새로 커밋할 때 추가될 예정입니다.
